import Head from "next/head";
import Image from "next/image";
import About from "../components/About";
import Contact from "../components/Contact";
import Landing from "../components/Landing";
import Navbar from "../components/Navbar";
import Work from "../components/Work";

export default function Home() {
  return (
    <div className="overflow-x-hidden">
      <Head>
        <title>notfort | Home </title>
        <meta lang="en" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/render.png" />
      </Head>

      <Navbar />
      <Landing />
      <Work />
      <About />
      <Contact />
    </div>
  );
}
